### ISSUE TITLE
Environment duplicated between pyopia and docs

### ISSUE THREAD

**Issue by animmosmith** [SINTEF/pyopia#127]
The docs folder contains an environment.yml. Should this automatically synchronise with that in the main pyopia folder?

**Comment by emlynjdavies** [comment]
I think this is because not all dependencies are needed to run the docs. (i.e. it should be possible to build the docs without installing tensorflow)

**Comment by emlynjdavies** [comment]
I think that initially the env file was just copied for convenience, so we should keep this issue open and test what happens if we reduce the dependencies in the docs environment.

**Comment by emlynjdavies** [comment]
could be done at the same time as fixing the issues relating to #131
