### ISSUE TITLE
Use color image for classifier

### ISSUE THREAD

**Issue by nordam** [SINTEF/pyopia#156]
When running the example in the notebook ```single-image-stats.ipynb```, the function ```statextract()``` gets passed an argument called ```imc```. In the pipeline in the example, ```imc``` is a 2D array, which means no colour information.

```data['imc']``` is converted to 2D by the function ```__call__()``` of the class ```ImagePrep```.

We should probably change this so that ```statextract()``` instead receives a background-corrected image with colour.

Two options for fixing this could be:
 * change ```ImagePrep.__call__()``` so it doesn't discard colour information in ```data['imc']```
 * pass ```data['imref']``` to the classifier instead.

It is not clear to me what is the best option, and if we need both ```data['imc']``` and ```data['imref']```.

**Comment by emlynjdavies** [comment]
I suggest passing imref to the classifier (I think this is what PySilCam did)
