### ISSUE TITLE
Make it possible to supply actual classes in the pipeline, instead of just a string pointing to a class defined in a file somewhere

### ISSUE THREAD

**Issue by nordam** [SINTEF/pyopia#160]
When you load a toml file, the representation of the pipeline will contain things like this:

```
'load': {'pipeline_class': 'pyopia.instrument.silcam.SilCamLoad'},
```

Here, ```'pyopia.instrument.silcam.SilCamLoad'``` is a string with the path to a class defined in a file somewher. Say that I want to use my own loader function, defined in a notebook. In such cases, it would be super convenient to be able to pass the class directly, which would make the same entry in the settings look something like this:

``` 
 'load': {'pipeline_class': __main__.SilCamLoad}
```

We could perhaps add some checks in ```step_callobj()``` to check if what is being passed is actually a string or a class, and then only do the string-parsing-stuff if needed.

**Comment by emlynjdavies** [comment]
You can add a custom code between steps, as explained [here](https://pyopia.readthedocs.io/en/latest/notebooks/pipeline_step_by_step.html#insert-an-add-hoc-step).

Alternatively, you can write your own pipeline-compatible class and insert it into the steps dictionary, for example:

```
class CustomLoad():
    def __init__(self):
        pass

    def __call__(self, data):
        img = np.load(data['filename'], allow_pickle=False)
        if img.shape[-1] == 1:
            # In this case, the image must be converted from Bayer to RGB
            img = cv2.cvtColor(img, cv2.COLOR_BayerBG2RGB)
        data['imraw'] = img
        data['timestamp'] = pd.to_datetime('2024' + os.path.splitext(os.path.basename(data['filename']))[0][6:])
        return data
```

This can be inserted into a toml file, as a step which looks like this:

```
[steps.load]
pipeline_class = 'entire.EntireLoad'
```
