### ISSUE TITLE
CreateBackground ignores custom load function

### ISSUE THREAD

**Issue by nordam** [SINTEF/pyopia#161]
When CreateBackground is to load images files, it goes looking for a function called 'load_image' in the relevant instrument module, ignoring any custom load functions that the pipeline might have been set up with. This is inconvenient for example if you want to load raw Bayer images, and have included conversion to RGB as part of the load function.

Suggest using the load function from the pipeline instead.

**Comment by nepstad** [comment]
This should be fixed by #166 - can you check that it does @nordam ?

**Comment by emlynjdavies** [comment]
Closing this as the fix is merged into the Dev-1.2 branch.

can reopen if we are not happy
