### ISSUE TITLE
Scaling of hologram ROI outputs incorrect

### ISSUE THREAD

**Issue by animmosmith** [SINTEF/pyopia#176]
Focussed ROI outputs from holograms appear binarised.

**Comment by emlynjdavies** [comment]
Hi @animmosmith Yes - I have become a little concerned about scaling issues.

Could you take a look at #172 https://github.com/SINTEF/pyopia/tree/91-the-name-imc-is-used-for-different-things-with-different-datatypes

and see let me know what you think?

**Comment by emlynjdavies** [comment]
Here is a link to the notebook, where we have been looking at a potential solution:

https://github.com/SINTEF/pyopia/blob/91-the-name-imc-is-used-for-different-things-with-different-datatypes/notebooks/pipeline-holo.ipynb

**Comment by emlynjdavies** [comment]
Please check the latest version of the [dev-1.2](https://github.com/SINTEF/pyopia/tree/dev-1.2.0) branch.

**Comment by emlynjdavies** [comment]
Closing this as the fix is merged into the Dev-1.2 branch.

can reopen if we are not happy
