### ISSUE TITLE
Jupyter notebook and matplotlib should be added to the environment file

### ISSUE THREAD

**Issue by nordam** [SINTEF/pyopia#26]
The repo contains example notebooks, but environment.yml does not include jupyter notebook. (Which may be intentionally?)

**Comment by emlynjdavies** [comment]
Yes, this should be an optional dependency and not part of the standard environment (also true for matplotlib).

See discussion about how to do this: https://github.com/SINTEF/pyopia/discussions/14

**Comment by animmosmith** [comment]
perhaps these should be included by default for increased usability by inexperienced users - and then omitted if required by those more expert.

**Comment by emlynjdavies** [comment]
Yep, OK. I agree usability should be prioritized, so perhaps just adding what is needed to the environment.yml is the best thing to do right now.

Eventually in the future, we could create a second environment-light.yml (or similar) for installing with minimal dependencies (i.e. just for running batch analysis jobs).
