### ISSUE TITLE
Investigate ncrcat for combining stats files?

### ISSUE THREAD

**Issue by nordam** [SINTEF/pyopia#308]
The command line tool ```ncrcat``` can combine netcdf files along a record dimension (commonly time). If we defined the dimension "index" as a record dimension, and made sure it was increasing across files, we could use ```ncrcat```.  Not sure if this would be faster than using ```open_mfdataset```, but maybe worth looking into? Note that it would require different threads to somehow keep, and syncronise, a running particle count, so it might not be feasible in practice.

**Comment by nepstad** [comment]
Version 2.5.11 introduced a new method for merging netcdf files which should solve the merge speed issue. Particle counts are available in the image_stats group in the netcdf files.
