### ISSUE TITLE
Dark im_corrected if using ".bmp" raw images

### ISSUE THREAD

**Issue by arsalanmstn** [SINTEF/pyopia#324]
The corrected image of a .bmp has float type values while its range is between 0 and 255. So the pipeline.data['im_corrected'] returns a dark image (overflowed values).

It seems that in SilCamLoad() class, the '.bmp': skimage.io.imread does not rescale the image to float64 in the range of (0,1).
Suggestion: modifying the code by defining a lambda function for '.bmp' extension as:
'.bmp': lambda f: skimage.io.imread(f).astype(np.float64) / 255}

**Comment by nepstad** [comment]
This sounds like a good solution, please do implement and create a pull request.
