### ISSUE TITLE
Consider handling of image types from different instruments

### ISSUE THREAD

**Issue by animmosmith** [SINTEF/pyopia#67]
Currently linked to 8 bit RGB

**Comment by emlynjdavies** [comment]
I think in terms of types, it might be best that analysis works on floats having scaled the range to a fix min and max.

i.e. loading functions should convert to floats and set the scaling somehow. then there would be no need for switching between unit8 and float, for example

**Comment by emlynjdavies** [comment]
in terms of image dimensions (number of channels). we may need to have logic in the analysis to handle differences, but i think that segmentation is best performed on a single-channel image (and a conversion to that might be contained within an ImagePrep step that is in one of the instrument subpackages, for example

**Comment by emlynjdavies** [comment]
we should convert to 0-1 floats

**Comment by emlynjdavies** [comment]
related to https://github.com/SINTEF/pyopia/issues/91

**Comment by nepstad** [comment]
We could make use of this function for simplicity: https://scikit-image.org/docs/stable/api/skimage.exposure.html#skimage.exposure.rescale_intensity

If the scaling and conversion to float is done at load time, it would make the codebase much easier to read I think.
