### ISSUE TITLE
Pipeline processing progress

### ISSUE THREAD

**Issue by animmosmith** [SINTEF/pyopia#83]
nice to have a "fancy" status output for the Pipeline so that progress is displayed, with elapsed and (estimated) remaining time to complete processing of all files in folder.

**Comment by emlynjdavies** [comment]
yes, the current printing outputs are a bit of a mess.

Ideally this should be done with, for example, logging: https://docs.python.org/3/library/logging.html
and the output level should be specified in some sort of configuration. how to setup such 'high-level' config should probably be something for discussion (and handled in a dedicated 'admin'-type module.

**Comment by emlynjdavies** [comment]
consider tqdm or this: https://rich.readthedocs.io/en/stable/progress.html
