### ISSUE TITLE
the name imc is used for different things, with different datatypes

### ISSUE THREAD

**Issue by nordam** [SINTEF/pyopia#91]
I'm working with the example pipeline in pipeline.ipynb

* The background correction step creates a background-corrected image, and stores it in ```data['imc']``` (short for image corrected, presumably?).
* The imageprep step then calls ```pyopia.instrument.silcam.ImagePrep```, which creates a scaled image, with floating point values between 0 and 1, and stores the result back into ```data['imc']```.
* This goes against the principle of not modifing input (although that is a separate philosophical discussion to be had, since the input is ```data```, which is modified all the time).
* It also breaks the example, since the later classification stop expects ```data['imc']``` to have values between 0 and 255, of type uint8.

**Comment by emlynjdavies** [comment]
also related to #173

**Comment by nepstad** [comment]
Improvements now available on the dev-1.2.0 branch, can you check @nordam ?

**Comment by emlynjdavies** [comment]
Closing this as the fix is merged into the Dev-1.2 branch.

can reopen if we are not happy
