### ISSUE TITLE
pixel size should be included in output files

### ISSUE THREAD

**Issue by animmosmith** [SINTEF/pyopia#96]
... as this will vary between instruments

**Comment by emlynjdavies** [comment]
i thought that pixel size was part of the inputs that would be in the metadata, together with other things like the threshold value etc

**Comment by animmosmith** [comment]
Yes - it is defined for the hologram processing, but not for SilCam. So we might want to have some extra metadata fields such as "Instrument" and "Pixel Size" that are required to be completed, or have sensible defaults. Otherwise, it would be to implement an extra data column within the "stats" data frame (wasteful) or to pre-scale the output from the region props to convert from pixels to microns etc.

**Comment by emlynjdavies** [comment]
Yes, I agree. This is also then a bit related to #65 and #36

**Comment by emlynjdavies** [comment]
This might be fixed using the config file solution that is anyway needed in #116. Then we can easily add this type of 'metadata' to the output files containing the STATS.

**Comment by animmosmith** [comment]
Yes - that sounds like a good approach
