### ISSUE TITLE
Installation description

### ISSUE THREAD

**Issue by sarigiering** [SINTEF/pyopia#99]
The current installation steps "Installing" are incomplete. When I followed the instructions, the test line "python setup.py develop" spits out the error message "error: package directory 'pyopia' does not exist".

**Comment by emlynjdavies** [comment]
I can try to create a .bat file that performs installation steps for a windows machine.

**Comment by sarigiering** [comment]
I updated the installation instructions. They should now be compatible for both: those that use git and those that don't (in which case there is a manual download of the repository).
So, I don't think we need an additional .bat file.

**Comment by emlynjdavies** [comment]
ok. perfect!
